-   id: version_checker
    name: Version checker
    description: Check if VERSION file was changed.
    entry: update_version.sh
    language: script
    pass_filenames: false
    types: [text]

-   id: change_log_checker
    name: CHANGELOG checker
    description: Check if CHANGELOG file was changed.
    entry: update_change_log.sh
    language: script
    pass_filenames: false
    type: [md]
